#!/usr/bin/env bash
# INSTALL NGINX

apt-get update
apt-get install -y nginx

printf %s "server {
  listen  80 default_server;
  root    /var/www/html;
  index   index.html index.htm;
  add_header X-Served-By $HOSTNAME;

  location /redirect_me {
    return 301 https://github.com/kaouthardev;
  }

  error_page 404 /custom_404.html;
  location = /custom_404.html {
    root /var/www/html;
    internal;
  }
}
" >/etc/nginx/sites-available/default
echo "Holberton School" >/var/www/html/index.html
echo "Ceci n'est pas une page" >/var/www/html/custom_404.html
service nginx restart
